name: clausemate
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=1.3.0
  - pip
  - pip:
    - -e .  # Install package in development mode
    # Development tools
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    - mypy>=1.0.0
    - ruff>=0.1.0
    - pre-commit>=2.20.0
    # Future dependencies (optional)
    # - spacy>=3.4.0
    # - scikit-learn>=1.0.0
    # - plotly>=5.0.0
